spring.datasource.h2.jdbcUrl=jdbc:h2:tcp://localhost/~/test
spring.datasource.h2.username=sa
spring.datasource.h2.password=
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.hikari.maximum-pool-size=10
spring.datasource.h2.hikari.connection-timeout=30000